static const char *sun_xpm[]={
"16 16 13 1",
"# c #000000",
". c #00ff00",
"a c #ffff00",
"e c #ffff06",
"f c #ffff07",
"d c #ffff46",
"g c #ffff49",
"k c #ffff4c",
"i c #ffff7f",
"c c #ffff80",
"b c #ffffb4",
"h c #ffffb5",
"j c #ffffb6",
"................",
".#a##########a#.",
".##a########a##.",
".####bccccb####.",
".###deaaaafg###.",
".##bfaaaaaaeh##.",
".##caaaaaaaai##.",
".##caaaaaaaai##.",
".aacaaaaaaaaiaa.",
".##caaaaaaaai##.",
".##beaaaaaafj##.",
".###gfaaaaek###.",
".####hiiiij####.",
".###a######a###.",
".##a########a##.",
"................"};

static const char *rain_xpm[]={
"16 16 5 1",
"# c #000000",
"c c #0000ff",
". c #00ff00",
"a c #808080",
"b c #ffffff",
"................",
".####aaaaaa####.",
".###abbbbbba###.",
".###abbbbbba###.",
".##aabbbbbbaa##.",
".#abbabbbbabba#.",
".abbbbbbbbbbbba.",
".abbbbbbbbbbbba.",
".abbbbbbbbbbbba.",
".#abbbbbbbbbba#.",
".##aaaaaaaaaa##.",
".###c###c###c##.",
".##c###c###c###.",
".#c###c###c####.",
".c###c###c#####.",
"................"};
