// font_common.h
// Shared definitions used by every font header generated by
// bdf_to_header.py. Generate/include this once per project even
// if you have multiple fonts.
#ifndef FONT_COMMON_H
#define FONT_COMMON_H

// Indices into every font's <prefix>_meta[] array.
enum {
    FONT_META_BBX_WIDTH = 0,
    FONT_META_BBX_HEIGHT,
    FONT_META_BBX_XOFF,
    FONT_META_BBX_YOFF,
    FONT_META_ASCENT,
    FONT_META_DESCENT,
    FONT_META_FIRST_CHAR,
    FONT_META_LAST_CHAR,
    FONT_META_NUM_CHARS,
    FONT_META_NOTDEF_OFFSET,
    FONT_META_COUNT
};

// Bundles a font's three generated arrays together so multiple
// fonts can be handled generically (e.g. an array of
// `const bdf_font_t *`) without any per-font macros.
typedef struct {
    const int *meta;   // FONT_META_COUNT ints, see enum above
    const int *data;   // packed glyph records (see font header comment)
    const int *index;  // [code - meta[FONT_META_FIRST_CHAR]] -> offset
                       // into data, or -1 if undefined
} bdf_font_t;

#endif // FONT_COMMON_H
